#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mailbag"
name = "MailBag"
description.en = "Simple plaintext email send app"
description.fr = "Application simple d'envoi d'e-mails en texte brut"

version = "2026.03.03~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
code = "https://codeberg.org/danb/mailbag"

[integration]
yunohost = ">= 12.2.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "350M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://codeberg.org/danb/mailbag/archive/a98dab573955764f71d0cbf4f02380eaaa8d4838.tar.gz"
        sha256 = "5fbcce99ded13e59ef89acc71cc7e312c6508ede3ff37002b257d7fff3628031"

    [resources.system_user]
    allow_email = true
    
    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "sqlite3, php8.4-bcmath, php8.4-mbstring, php8.4-sqlite3, php8.4-xml"

    [resources.composer]
    version = "2.9.5"

    [resources.nodejs]
    version = "22"
