#!/bin/bash

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run $1
