#!/bin/bash

source /usr/share/yunohost/helpers

email=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod -R g+w "$install_dir/storage"
chmod -R g+w "$install_dir/bootstrap/cache"

#=================================================
# INSTALL COMPOSER DEPENDENCIES
#=================================================
ynh_script_progression "Installing composer dependencies..."

ynh_composer_exec install --no-dev

#=================================================
# SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

yunohost service add "$app" --description="Mailbag Queue" --log="/var/log/$app/$app.log"

#=================================================
# ADD ENV
#=================================================
ynh_script_progression "Adding a configuration file..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# APP INSTALL
#=================================================
ynh_script_progression "Install $app"

pushd $install_dir
	ynh_exec_as_app php$php_version artisan key:generate
	ynh_exec_as_app touch storage/database/database.sqlite
	ynh_exec_as_app php$php_version artisan migrate --no-interaction --force

	ynh_hide_warnings npm install
	ynh_hide_warnings ynh_exec_as_app npm run build
	ynh_exec_as_app php$php_version artisan mailbag:add-user <<EOF
$admin
$email
$password
EOF
	sed -i "/'url' => env('APP_URL', 'http:\/\/localhost'),/a \ \ \ \ 'home_redirect_url' => env('HOME_REDIRECT_URL')," config/app.php
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting a systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"