#!/bin/bash

source /usr/share/yunohost/helpers

email=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

yunohost service add $app --description="MailBag Queue" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL AND INITIALIZE COMPOSER
#=================================================
ynh_script_progression "Installing Composer..."

ynh_composer_exec install --no-dev

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# FINAL MAILBAG INSTALL
#=================================================
ynh_script_progression "Install $app"

pushd $install_dir
	php$php_version artisan key:generate --no-interaction --force
	touch storage/database/database.sqlite
	php$php_version artisan migrate --no-interaction --force

	ynh_hide_warnings ynh_exec_as_app npm install
	ynh_hide_warnings ynh_exec_as_app NODE_ENV=production npm run build
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
