#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_config_remove_phpfpm

ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
