#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep=".env storage/database/database.sqlite"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate "$install_dir/storage/logs/laravel.log"

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

yunohost service add $app --description="MailBag Queue" --log="$install_dir/storage/logs/laravel.log"

#=================================================
# INSTALL AND INITIALIZE COMPOSER
#=================================================
ynh_script_progression "Installing Composer..."

ynh_composer_exec install --no-dev

#=================================================
# APP INSTALL
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
	php$php_version artisan migrate --no-interaction --force

	ynh_hide_warnings ynh_exec_as_app npm install
	ynh_hide_warnings ynh_exec_as_app npm run build

	php$php_version artisan queue:restart
	php$php_version artisan config:cache
	php$php_version artisan route:cache
	php$php_version artisan view:cache
popd

chown -R "$app:www-data" "$install_dir/storage"
chown -R "$app:www-data" "$install_dir/bootstrap/cache"

chmod -R g+w "$install_dir/storage"
chmod -R g+w "$install_dir/bootstrap/cache"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
